name: Build and Upload APK

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission
      run: chmod +x gradlew

    - name: Build and Zip APK
      run: |
        ./gradlew assembleRelease
        zip -r release.zip $GITHUB_WORKSPACE/app/build/outputs/apk/release/

    - name: Upload Release APK to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip
