name: Build and Upload APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission
      run: chmod +x gradlew

    - name: Build APK
      run: |
        ./gradlew assembleRelease

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Git
      run: |
        git -C $GITHUB_WORKSPACE config user.email "rashed162@gmail.com"
        git -C $GITHUB_WORKSPACE config user.name "rashed-imam"
        TAG_NAME=$(git -C $GITHUB_WORKSPACE log --pretty=format:'%h' -n 1)
        git -C $GITHUB_WORKSPACE tag -a $TAG_NAME -m "Version $TAG_NAME"
        git -C $GITHUB_WORKSPACE push origin $TAG_NAME
        
    - name: Upload Release APK to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
